In [1]:
import gym

env = gym.make('FrozenLake-v0')

print(env.observation_space.n)
print(env.action_space.n)

env.reset()

16
4


0

In [3]:
action = env.action_space.sample()
observation, reward, done, info = env.step(action)
env.render()

  (Right)
SFFF
FHFH
FFFH
HFFG


In [4]:
import gym
import numpy as np
import time

env = gym.make('FrozenLake-v0')
STATES = env.observation_space.n
ACTIONS = env.action_space.n
Q = np.zeros((STATES, ACTIONS))

In [5]:
EPISODES = 10000
MAX_STEPS = 100

LEARNING_RATE = 0.01
GAMMA = 0.96

In [7]:
# Picking an action
eps = 0.9

if np.random.uniform(0, 1)<eps:
    action = env.action_space.sample()
else:
    action = np.argmax(Q[state, :])

In [8]:
# Update Q Values
Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMMA*np.max(Q[new_state, :]) - Q[state, action])

NameError: name 'state' is not defined

In [18]:
# Example

import gym
import numpy as np
import time

env = gym.make('FrozenLake-v0')
STATES = env.observation_space.n
ACTIONS = env.action_space.n
Q = np.zeros((STATES, ACTIONS))

EPISODES = 1500
MAX_STEPS = 100

LEARNING_RATE = 0.8
GAMMA = 0.96

eps = 0.9

RENDER = False

rewards = []
for episode in range(EPISODES):
    state = env.reset()
    for _ in range(MAX_STEPS):
        if RENDER:
            env.render()
        if np.random.uniform(0, 1)<eps:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state, :])

        next_state, reward, done, _ = env.step(action)

        Q[state, action] = Q[state, action] + LEARNING_RATE * (reward + GAMMA*np.max(Q[next_state, :]) - Q[state, action])

        state = next_state

        if done:
            rewards.append(reward)
            eps -= 0.001
            break

In [19]:
print(Q)
print(sum(rewards)/len(rewards))

[[1.66940182e-02 4.86292691e-01 1.64444828e-02 1.66735903e-02]
 [5.35504107e-03 4.23063710e-03 5.15380919e-03 3.19358163e-01]
 [8.11917676e-03 3.68036998e-03 6.09751680e-03 1.65102411e-01]
 [6.90553366e-03 5.77388070e-03 2.56517557e-03 5.94264567e-02]
 [4.79683166e-01 2.85460383e-03 7.08910821e-03 6.38212515e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.44059829e-02 9.93587111e-05 8.83412152e-05 5.64938525e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.04180363e-03 3.36043720e-03 1.01726906e-02 4.83567042e-01]
 [2.36726188e-03 2.61323104e-01 4.38764579e-03 4.36609273e-03]
 [8.02164391e-01 8.61341174e-04 1.80697675e-03 1.63787709e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.13076316e-02 2.63621911e-02 5.12045701e-01 9.17585554e-02]
 [2.06362766e-01 9.98405037e-01 1.28897172e-01 2.08486923e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [21]:
import matplotlib.pyplot as plt

def get_average(values):
    return sum(values)/len(values)

avg_rewards = []
for i in range(0, len(rewards), 100):
    avg_rewards = get_average(rewards[i:i+100])

plt.plot(avg_rewards)
plt.ylabel('average reward')
plt.xlabel('episdes (100\'s)')
plt.show()

ModuleNotFoundError: No module named 'matplotlib'